AllCops:
  TargetRubyVersion: 2.7.4
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: 'never'

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'