name: Ruby Gem CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]
    on:
      push:
        tags:
          - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.7', '3.0', '3.1', '3.2', '3.3']

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Install Bundler for Ruby < 3.0
        if: ${{ matrix.ruby-version < '3.0' }}
        run: gem install bundler -v 2.4.22 --no-document

      - name: Install Bundler for Ruby >= 3.0
        if: ${{ matrix.ruby-version >= '3.0' }}
        run: gem install bundler -v '~> 2.5' --no-document

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Run tests and linting
        run: bundle exec rake

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/.resultset.json
          fail_ci_if_error: false

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby for publish
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - name: Install dependencies
        run: |
          gem install bundler --no-document
          bundle install --jobs 4 --retry 3

      - name: Build gem
        run: |
          gem build *.gemspec

      - name: Push gem to RubyGems
        run: |
          gem push *.gem
        env:
          GEM_HOST_API_KEY: ${{secrets.GEM_HOST_API_KEY}}