name: Ruby Gem CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.6', '2.7', '3.0']

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Install dependencies
        run: |
          gem install bundler --no-document
          bundle install --jobs 4 --retry 3

      - name: Run tests and linting
        run: bundle exec rake

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby for publish
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install dependencies
        run: |
          gem install bundler --no-document
          bundle install --jobs 4 --retry 3

      - name: Build gem
        run: |
          gem build *.gemspec

      - name: Push gem to RubyGems
        run: |
          gem push *.gem --api-key ${{secrets.RUBYGEMS_AUTH_TOKEN}}